sudo: false
language: c

matrix:
  include:
    - env: GHCVER=7.8.4 STACK_LTS=lts-2 STACK_TEMPLATE=stack-lts-2.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.8.4 ]
    - env: GHCVER=7.10.2 STACK_LTS=lts-3 STACK_TEMPLATE=stack-lts-3.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.2 ]
    - env: GHCVER=7.10.3 STACK_LTS=lts-5 STACK_TEMPLATE=stack-lts-5.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.3 ]
    - env: GHCVER=7.10.3 STACK_LTS=lts-5 STACK_TEMPLATE=stack-lts-5-aeson11.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.3 ]
    - env: GHCVER=7.10.3 STACK_LTS=lts-6 STACK_TEMPLATE=stack-lts-6.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.3 ]

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - m4 -D__RESOLVER__=$(curl -sL https://www.stackage.org/download/snapshots.json | jq '."'$STACK_LTS'"' -r) .travis/$STACK_TEMPLATE > stack.yaml

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - travis_wait stack --no-terminal --skip-ghc-check test
  - stack sdist
  - chmod 755 ./attic/check-sdist.sh
  - ./attic/check-sdist.sh twitter-types
  - ./attic/check-sdist.sh twitter-types-lens

cache:
  directories:
    - ~/.stack
