language: sh
sudo: required

env:
  matrix:
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=7.8.4
    - GHCVER=7.10.1
    - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=7.4.2
    - env: GHCVER=head

before_install:
  - eval "$( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )"
  - export HALCYON_GHC_VERSION=$GHCVER HALCYON_CABAL_VERSION=1.22.4.0

install:
  - cd twitter-types
  - HALCYON_SANDBOX_EXTRA_APPS="hpc-coveralls happy" HALCYON_SANDBOX_EXTRA_CONFIGURE_FLAGS="--enable-tests --only-dependencies" halcyon install

script:
  - cabal sandbox init --sandbox=/app/sandbox/
  - cabal configure --enable-tests --enable-library-coverage
  - run-cabal-test --cabal-name=cabal --show-details=always

  - cd ../twitter-types-lens
  - halcyon install --sandbox-sources=../twitter-types

after_script:
  - cd ../twitter-types && hpc-coveralls --exclude-dir=tests tests
