sudo: false
language: c

matrix:
  include:
    - env: GHCVER=7.8.4 STACK_YAML=stack-lts-2.yml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.8.4 ]
    - env: GHCVER=7.10.2 STACK_YAML=stack-lts-3.yml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.1 ]

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check install hpc-coveralls
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - travis_wait stack --no-terminal --skip-ghc-check test --coverage

after_script:
  # for hpc-coveralls
  - stack --no-terminal --skip-ghc-check exec .travis/copy_stack_dist.sh
  - cd twitter-types && hpc-coveralls --exclude-dir=tests tests

cache:
  directories:
    - ~/.stack
